eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: alarm-service
  kafka:
    bootstrap-servers: kafka-service:9092
    consumer:
      group-id: alarm-group
      auto-offset-reset: earliest
    topic:
      name: alarm-topic

server:
  port: 0
