spring:
  config:
    activate:
      on-profile: local
  application:
    name: alarm-service
  kafka:
    bootstrap-servers: indie7942.store:9092
    consumer:
      group-id: alarm-group
      auto-offset-reset: earliest
    topic:
      name: alarm-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0
