eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: control-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/controller-msa
    username: postgres
    password: ${DB_PW}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: kafka-service:9092
    topic:
      name: alarm-topic

server:
  port: 0
