spring:
  config:
    activate:
      on-profile: local
  application:
    name: temp-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/controller-msa
    username: postgres
    password: 1234
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: indie7942.store:9092
    consumer:
      group-id: alarm-group
      auto-offset-reset: earliest
    topic:
      name: alarm-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0
