eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: apigateway-service

  cloud:
    gateway:
      server:
        webflux:
          # CORS 설정 (globalcors → server.webflux.globalcors)
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - '*'
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - '*'
                allowedCredentials: true
          # 라우팅 설정
          routes:
            - id: control-service
              predicates:
                - Path=/control-service/**
              filters:
                - StripPrefix=1
              uri: http://control-service

            - id: alarm-service
              predicates:
                - Path=/alarm-service/**
              filters:
                - StripPrefix=1
              uri: http://alarm-service

            - id: temp-service
              predicates:
                - Path=/temp-service/**
              filters:
                - StripPrefix=1
              uri: http://temp-service